---
- name: reset | check kube-dummy-if network device
  stat:
    path: /sys/class/net/kube-dummy-if
  register: kube_dummy_if

- name: reset | remove the network device created by kube-router
  command: ip link del kube-dummy-if
  when: kube_dummy_if.stat.exists
