kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-grafana
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/grafana"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-grafana
  namespace: monitoring
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
--- 
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-grafana-extra
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/grafana"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-grafana-extra
  namespace: monitoring
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
