---
docker_kernel_min_version: '3.10'

use_docker_engine: false

docker_versioned_pkg:
  'latest': docker-ce
  '18.03': docker-ce=18.03.1~ce-3-0~ubuntu
  '18.06': docker-ce=18.06.1~ce~3-0~ubuntu
  '18.09': docker-ce_18.09.1~3-0~ubuntu-{{ ansible_distribution_release|lower }}
  'stable': docker-ce=18.06.1~ce~3-0~ubuntu
  'edge': docker-ce=18.06.1~ce~3-0~ubuntu

docker_package_info:
  pkg_mgr: apt
  pkgs:
    - name: "{{ docker_versioned_pkg[docker_version | string] }}"
      force: yes

docker_repo_key_info:
  pkg_key: apt_key
  url: '{{ docker_ubuntu_repo_gpgkey }}'
  repo_keys:
    - 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

docker_repo_info:
  pkg_repo: apt_repository
  repos:
    - >
       deb [arch=amd64] {{ docker_ubuntu_repo_base_url }}
       bionic
       stable
